### ISSUE TITLE
Wide content requires scrolling

### ISSUE THREAD

**Issue by bvibber** [yuvipanda/WPSignpost#10]
Wide images should be scaled down to fit. There's an image ("The interior of the Hagia Sophia Church ...") on current issue's 'Featured content' section which is much too wide, and requires horizontal scrolling.

**Comment by yuvipanda** [comment]
But wouldn't crunching it make it impossible to view?

**Comment by yuvipanda** [comment]
overflow-y scrolling now set. You can scroll just that particular thumbnail container :) Needs a better indicator for that, however.
