### ISSUE TITLE
WPSignpost -> Signpost or other

### ISSUE THREAD

**Issue by Jarry1250** [yuvipanda/WPSignpost#20]
We dropped the "Wikipedia" a while back. The Signpost, perhaps?

**Comment by yuvipanda** [comment]
The app's name is just 'Signpost'. WP is just this repository's name, and is present in the identifier. Since they're both internal, I guess this is okay?

**Comment by Jarry1250** [comment]
It appears under Manage > Applications, which is A-Z sorted, adding to the confusion.

**Comment by yuvipanda** [comment]
I seem to have missed that, changed it now.
