### ISSUE TITLE
Title Link is incorrect

### ISSUE THREAD

**Issue by Parent5446** [yuvipanda/WPSignpost#26]
When reading an article, the title at the top is also a link to open a web browser for the article. Clicking on the link brings the user to "http://en.wikipedia.org/en.wikipedia.org/...". Some duplication of the authority is occurring. Luckily WMF is nice and redirects the user to the correct page, but should probably be fixed.

**Comment by yuvipanda** [comment]
Thanks for reporting this! I don't see what use could come off having that as a link (it doesn't even look like one), so I've removed the link :)
