### ISSUE TITLE
Support for Single-page version.

### ISSUE THREAD

**Issue by Parent5446** [yuvipanda/WPSignpost#27]
More of a feature request, but I usually like to read the Signpost in its single-page version. It'd be nice if there was a link or bar of some sort at the top of an edition (underneath the header) that brings you to a single page with all the articles.

**Comment by yuvipanda** [comment]
Wouldn't implementing #5 sortof nullify this, so you can simply swipe around and read instead of hit back -> scroll again -> tap again and read?

**Comment by Parent5446** [comment]
Hmm, yeah, good point. I'll close this, then.
