### ISSUE TITLE
Sharing link doesn't include protocol.

### ISSUE THREAD

**Issue by Parent5446** [yuvipanda/WPSignpost#28]
When using the Share feature on an article, the link given does not have a protocol, i.e., it is just "en.wikipedia.org/...". This is not a major problem, but without the protocol it will not be automatically linked in many sharing apps. With the protocol, apps like Gmail will automatically convert it into a link.

**Comment by yuvipanda** [comment]
Thanks a lot for reporting this :) Has been fixed!
