### ISSUE TITLE
App failed to launch

### ISSUE THREAD

**Issue by Uwanja** [yuvipanda/WPSignpost#40]
App successfully installed but failed to launch.

Error message: "The application Signpost (process in.yuvi.signpost) has stopped unexpectedly.Please try again."

**Comment by yuvipanda** [comment]
Can you tell me which phone and which version of Android you are using?

**Comment by Uwanja** [comment]
Am using the Huawei IDEOS U8150 as at http://www.gsmarena.com/huawei_u8150_ideos-3513.php
Android version 2.2.1 
Dronix 0.4
Kernel version 2.6.32.9-perf esteban@hpmonster #16
Hope that helps.

**Comment by yuvipanda** [comment]
Possibly fixed in the same commit that fixed #46. Can you test and confirm?

**Comment by yuvipanda** [comment]
Fixed, confirmed on Facebook! :)

**Comment by Uwanja** [comment]
Receipt acknowledged...an confirmed once again via this comment

//Stephen

On Tue, Aug 28, 2012 at 4:56 AM, Yuvi Panda notifications@github.comwrote:

> Fixed, confirmed on Facebook! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yuvipanda/WPSignpost/issues/40#issuecomment-8089060.

## 

"If Wikipedia is good enough for the Archivist of the United States,
maybe it should be good enough for you." - US Archivist ,David Ferriero.

"Imagine a world in which every single human being can freely share in
the sum of all knowledge."  Help us make it a reality!
Donate to Wikimedia https://donate.wikimedia.org/
