### ISSUE TITLE
app does not update with the new issue

### ISSUE THREAD

**Issue by ragesoss** [yuvipanda/WPSignpost#41]
The new Signpost (August 20 edition) isn't showing up. The app still shows the August 13 issue, which was the newest one when I installed the latest Beta1 apk.

**Comment by ragesoss** [comment]
After multiple times of opening and closing the app, it finally decided to update to the new issue. I'm not sure why it did that, or how to force it to update next time, though.

**Comment by yuvipanda** [comment]
Sure? I see the latest issue all right

**Comment by ragesoss** [comment]
Under what circumstances does the app search for new content? A refresh button would be good, I think, for when users are anxiously awaiting the new issue and can't bring themselves to do anything but check over and over if it's ready yet.

**Comment by yuvipanda** [comment]
The app currently checks only on initial start - so a single force kill should've done it. I'll add a 'Latest issue' button someplace

**Comment by ragesoss** [comment]
Okay. It must have been that the app was still hanging around in memory for
a long time without being killed. Probably a common situation for newer
phones.

(sent from my phone)

**Comment by yuvipanda** [comment]
In this case it was also the case that I had forgotten to run the cronjob that updates the issues (haven't set it up yet), and ran it manually only when I saw this issue :P That explains the extra delays.

**Comment by ragesoss** [comment]
So it phones home to the toolserver or something for new issues?

(sent from my phone)

**Comment by yuvipanda** [comment]
It hits my server (at yuvi.in/signpost). See the api/ folder here to see the code that runs there

**Comment by yuvipanda** [comment]
Fixed. Added a menu item 'See latest Issue'. Suggestions for better wording welcome!
