### ISSUE TITLE
Eclipse

### ISSUE THREAD

**Issue by reedy** [yuvipanda/WPSignpost#50]
Why won't Eclipse open this as a project!? =(

**Comment by yuvipanda** [comment]
It does for me! Import Project didn't work?

On Wed, Sep 5, 2012 at 4:12 AM, Sam Reed notifications@github.com wrote:

> Why won't Eclipse open this as a project!? =(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yuvipanda/WPSignpost/issues/50.

## 

Yuvi Panda T
http://yuvi.in/blog

**Comment by reedy** [comment]
Eclipse says there are no projects to import when I select a checkout of WPSignpost.

Same method worked fine for WP Mobile, WLM et al.

Have you some local files not added/comitted?

**Comment by yuvipanda** [comment]
How about now?

On Wed, Sep 5, 2012 at 7:24 PM, Sam Reed notifications@github.com wrote:

> Eclipse says there are no projects to import when I select a checkout of
> WPSignpost.
> 
> Same method worked fine for WP Mobile, WLM et al.
> 
> Have you some local files not added/comitted?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yuvipanda/WPSignpost/issues/50#issuecomment-8299488.

## 

Yuvi Panda T
http://yuvi.in/blog

**Comment by reedy** [comment]
Yup, that fixes it.

Thanks!
