### ISSUE TITLE
You broke the build!

### ISSUE THREAD

**Issue by reedy** [yuvipanda/WPSignpost#55]
Eclipse is unhappy, again..

Description Resource    Path    Location    Type
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.Sherlock.Light'.  styles.xml  /WPSignpost/res/values-v11  line 3  Android AAPT Problem
Project 'WPSignpost' is missing required Java project: 'ActionBarSherlock'  WPSignpost      Build path  Build Path Problem
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.Sherlock.Light'.  styles.xml  /WPSignpost/res/values  line 4  Android AAPT Problem
The project cannot be built until build path errors are resolved    WPSignpost      Unknown Java Problem
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.Sherlock.Light'.  styles.xml  /WPSignpost/res/values-v14  line 3  Android AAPT Problem

**Comment by yuvipanda** [comment]
So... Damn Eclipse :P I've switched to IntelliJ and it works fine for it now. Eventually should add maven support, so Eclipse / IntelliJ / Vim / Emacs users can all be happy.
